device: "cuda"

model:
  backbone: "resnet18"
  hidden_dim: 512
  pretrained: False

data:
  path: "./data/"
  s: 1.0
  input_shape: [96, 96]

train:
  epochs: 100
  batch_size: 32
  lr: 3E-4
  momentum: 0.998
  weight_decay: 1E-4
  log_interval: 100
  log_dir: "./logs"
