device: "cuda"

model:
  backbone: "resnet50"
  latent_dim: 2048
  proj_hidden_dim: 2048
  pred_hidden_dim: 512
  pretrained: False
  weights_path: "models/pretrain.pt"

data:
  path: "data/"
  train_pct: 0.01
  input_shape: [96, 96]

train:
  epochs: 25
  batch_size: 256
  lr: 0.03
  momentum: 0.9
  weight_decay: 0.0
  log_interval: 100
  log_dir: "logs/"
